export enum ActionEnum {
    /* Organization */

    CREATE_ORGANIZATION = 'CREATE_ORGANIZATION',
    VERIFY_ORGANIZATION = 'VERIFY_ORGANIZATION',
    EDIT_ORGANIZATION = 'EDIT_ORGANIZATION',
    VIEW_ORGANIZATION = 'VIEW_ORGANIZATION',
    UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION',

    /* Student */
    CREATE_STUDENT = 'CREATE_STUDENT',
    VERIFY_STUDENT = 'VERIFY_STUDENT',
    EDIT_STUDENT = 'EDIT_STUDENT',
    VIEW_STUDENT = 'VIEW_STUDENT',
    UPDATE_STUDENT = 'UPDATE_STUDENT',

    /* Teacher */
    CREATE_TEACHER = 'CREATE_TEACHER',
    VERIFY_TEACHER = 'VERIFY_TEACHER',
    EDIT_TEACHER = 'EDIT_TEACHER',
    VIEW_TEACHER = 'VIEW_TEACHER',
    UPDATE_TEACHER = 'UPDATE_TEACHER',

    /* Online Class */

    /* Branch */
    CREATE_BRANCH = 'CREATE_BRANCH',
    VERIFY_BRANCH = 'VERIFY_BRANCH',
    EDIT_BRANCH = 'EDIT_BRANCH',
    VIEW_BRANCH = 'VIEW_BRANCH',
    UPDATE_BRANCH = 'UPDATE_BRANCH',

    /* Dobut */

    /* Organization Type */
    GET_ORG_TYPE = 'GET_ORG_TYPE',
    ADD_ORG_TYPE = 'ADD_ORG_TYPE',
    UPDATE_ORG_TYPE = 'UPDATE_ORG_TYPE',
}